### ISSUE TITLE
IFFT

### ISSUE THREAD

**Issue by IPrium** [yellowko/3780fft#1]
Hello
Can you suggest how to make IFFT (Inverse FFT) with your code?

**Comment by yellowko** [comment]
You can use FFT to make IFFT like this:
> **x[n]=(FFT((X[k])<sup>\*</sup>))<sup>\*</sup>**/N    

The derivation process is as follows：
> We kown DFT like this
>> <a href="https://www.codecogs.com/eqnedit.php?latex=X[k]=DFT(x[n])=\sum_{n=0}^{N-1}x[n]W_{N}^{kn}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?X[k]=DFT(x[n])=\sum_{n=0}^{N-1}x[n]W_{N}^{kn}" title="X[k]=DFT(x[n])=\sum_{n=0}^{N-1}x[n]W_{N}^{kn}" /></a>    
>>    
>>    
>> <a href="https://www.codecogs.com/eqnedit.php?latex=x[n]=IDFT(X[k])=\frac{1}{N}\sum_{k=0}^{N-1}X[k]W_{N}^{-kn}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x[n]=IDFT(X[k])=\frac{1}{N}\sum_{k=0}^{N-1}X[k]W_{N}^{-kn}" title="x[n]=IDFT(X[k])=\frac{1}{N}\sum_{k=0}^{N-1}X[k]W_{N}^{-kn}" /></a>    

> Then you can take it twice conjugate
>> <a href="https://www.codecogs.com/eqnedit.php?latex=x[n]=\left&space;(&space;\left&space;(&space;\frac{1}{N}\sum_{k=0}^{N-1}X[k]W_{N}^{-kn}&space;\right&space;)^{*}\right&space;)^{*}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x[n]=\left&space;(&space;\left&space;(&space;\frac{1}{N}\sum_{k=0}^{N-1}X[k]W_{N}^{-kn}&space;\right&space;)^{*}\right&space;)^{*}" title="x[n]=\left ( \left ( \frac{1}{N}\sum_{k=0}^{N-1}X[k]W_{N}^{-kn} \right )^{*}\right )^{*}" /></a>    
>>    
>>    
>> <a href="https://www.codecogs.com/eqnedit.php?latex=x[n]=\left&space;(&space;\frac{1}{N}\sum_{k=0}^{N-1}\left&space;(&space;X[k]\right&space;)^{*}W_{N}^{kn}&space;\right&space;)^{*}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x[n]=\left&space;(&space;\frac{1}{N}\sum_{k=0}^{N-1}\left&space;(&space;X[k]\right&space;)^{*}W_{N}^{kn}&space;\right&space;)^{*}" title="x[n]=\left ( \frac{1}{N}\sum_{k=0}^{N-1}\left ( X[k]\right )^{*}W_{N}^{kn} \right )^{*}" /></a>    
>>    
>>    
>> <a href="https://www.codecogs.com/eqnedit.php?latex=x[n]=\frac{1}{N}\left&space;(&space;DFT\left&space;(&space;\left&space;(X[k]\right&space;)^{*}\right&space;)\right&space;)^{*}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x[n]=\frac{1}{N}\left&space;(&space;DFT\left&space;(&space;\left&space;(X[k]\right&space;)^{*}\right&space;)\right&space;)^{*}" title="x[n]=\frac{1}{N}\left ( DFT\left ( \left (X[k]\right )^{*}\right )\right )^{*}" /></a>

**Comment by IPrium** [comment]
it works! thank you
